### ISSUE TITLE
Funding Reporting: I can submit my OEC funding reports through ECE Reporter

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/component-library#118]

**Comment by jay-finch** [comment]
Does Emily have all the learnings she needs from this?

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 You two wanna keep this ticket around, or close it in favor of future funding report tickets?

**Comment by ehuang525** [comment]
@JordanGuinn I don't think we need this so I'm good with deleting.
