### ISSUE TITLE
As an OEC Staff Member, I can go through the File Upload process with minimal friction 

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/component-library#139]
## Background
The file upload process could be edited/enhanced. Currently, the [file upload process](https://staging.ece-fawkes.ctoecskylight.com/upload) contains too many steps and could be simplified. 

## Acceptance Criteria

The upload process will no longer require the progress bar and will now only contain two steps: 1) Upload data + 2) Confirm and save, as described below:

**Pt 1 - Upload Data**
- Copy and image is displayed according to design mockup
- The linked "data collection template" text in the copy should link to: https://ece-reporter.ctoec.org/template
- The container for file upload is widened out and contains copy as shown in design mockup.

**Pt 2 - Confirm and Save**
After the file upload is processed, this page displays a summary of the file upload in 4 cards: 
- total number of records in file
- new records
- updated records
- withdrawn records.

A table view of the records that have been uploaded is displayed:
- Columns contain: Name, Update, Age group, Funding type, Space type, Site, and Enrollment date.
- The 4 update types are: New Record, Withdrawn, Enrollment or Funding Change, Edited Info
- Records with missing information/errors will display the error icon next to the name. Rows with errors will be automatically expanded upon landing on this page, surfacing the errors associated with that record.

Clicking 'Save changes to roster' will process the file upload.
Clicking 'Cancel' will discard the upload take the user back to the main upload file page.

## Designs
**Figma Link**

https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=21%3A0

![Screen Shot 2021-04-29 at 4.04.41 PM.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/819403a1-43db-430f-9245-677ef9959ab0)

**Comment by JordanGuinn** [comment]
Keeping as a single ticket because it all needs to be released in one fell swoop, so there's no real value in breaking it up.
