### ISSUE TITLE
Draft: As an OEC Admin User, I can view, create, and edit organization's information. I can also edit another user's information

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/component-library#147]
## Background
OEC Admin users should have the ability to view all organization information in a tabular view, create new organizations, edit any organization, and also edit any user's information within ECE Reporter. This will allow stakeholders from OEC to manage data within ECE Reporter appropriately, allowing OEC users to be more autonomous as we prepare for handoff in September while reducing time spent manually adding or editing specific pieces of data. 

## Acceptance Criteria

1. **OEC Admin Tabular View** has been created and wired up. 
  - View is treated as "homepage" for OEC Admin users 
2. **OEC Admin Create Organization** has been created and wired up.
  - View can be accessed from clicking on "Create New Organization" button from OEC Admin Tabular View
3. **OEC Admin Edit Organization** has been created and wired up.
  - View can be accessed...
4. **OEC Admin Edit User** has been created and wired up.
  - View can be accessed...

**Comment by JordanGuinn** [comment]
@Derekskylight Moving forward can you ensure that the tickets created are within the appropriate repository?  This epic and all the tickets under it exist in the `component-library` repo, which is just the collection of React components that our application uses.  Generally you're gonna wanna select `data-collection` 🙂

**Comment by Derekskylight** [comment]
Got it sorry about that! Would you like me to close these and open these tickets under the data-collection repo? It won't take too long and if we'd like to maintain a clean zenhub I'd be happy to

**Comment by JordanGuinn** [comment]
If it doesn't take too long, sure!  I'm VERY onboard with keeping our backlog clean and tidy 😁👏🏽

**Comment by Derekskylight** [comment]
Yup closed and opened with new tickets for data-collection!
