### ISSUE TITLE
Refactor DateInput component for OEC Component Library

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/component-library#3]
The `DateInput` component needs to be updated to simplify the API and remove `_Old` variables/functions and better handle onChange/onBlur distinctions

**Comment by mmazanec22** [comment]
Consult with @RyanHansz about possibility of following USWDS recommendation of using three separate fields instead of one textinput

**Comment by RyanHansz** [comment]
@mmazanec22 I'm for the separate inputs! I had that recommendation at one point after doing some research, but it got lost in the shuffle
