### ISSUE TITLE
Make a decision on InlineIcon vs TextWithIcon

### ISSUE THREAD

**Issue by jlhogan** [ctoec/component-library#5]
currently two Components exist that do similar things:
- `InlineIcon`, which handles the svg imports and takes a string `icon` prop to determine which svg to render
- `TextWithIcon` which takes a string `text` prop, and an SVGElement function component `Icon` prop and renders them both

`TextWithIcon` is more modular and probably what we should use

**Comment by mmazanec22** [comment]
We should use TextWithIcon and also get rid of the TextInput type `inline-input`

**Comment by jlhogan** [comment]
TextInput type seems totally separate. But also, is needed to put text on either side of a TextInput but keep it associated with an input label

**Comment by mmazanec22** [comment]
Can we use TextWithIcon for the label?

**Comment by jlhogan** [comment]
I don't understand how these are related at all. inline text input: 
![Screenshot from 2020-07-09 15-42-21](https://user-images.githubusercontent.com/54035880/87083549-ccca0d80-c1fa-11ea-8ce7-dcb5a20714f7.png)

no icons to be seen

**Comment by mmazanec22** [comment]
Ah right nvm, I forgot the use case-- maybe I will make myself a note for next time I forget what this is

**Comment by jlhogan** [comment]
yeah comments in the code are a v good idea!!

**Comment by JordanGuinn** [comment]
Is this ticket `Done`?  I see it was closed, then reopened
